name = "my-tunn-node-0128" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"

#main = "test/worker/worker-connect-test.js"
main = "src/worker-vless.js"

compatibility_date = "2024-04-15"

[vars]
UUID = "c3caf142-040b-464f-b716-bba076448f6d"
